### ISSUE TITLE
Upper pillbox not loading

### ISSUE THREAD

**Issue by Flexiboi** [Bob74/bob74_ipl#101]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes

**Describe the bug**
Upper pillbox near legionsquare not loading on first start
After I manualy restart the ipl loader it loads in.
Even changed from early fivem version to newer still same problem.
Just a hole in the ground.

**To Reproduce**
Pillbox

**Expected behavior**
/

**Screenshots**
/

**Versions**
 - latest
 - latest

**Comment by FrogCF** [comment]
I can confirm since latest update pill box don't work anymore
