### ISSUE TITLE
Vangelico - Outside are holes.

### ISSUE THREAD

**Issue by GameBoyNL** [Bob74/bob74_ipl#105]
Hello, i just noticed that outside Vangelico Jewel Store, the place has a hole and if you walk, you fall into void. And on the stair side you also fall through the void.
![image](https://user-images.githubusercontent.com/62553416/186273355-0118e996-140a-4c14-9230-871f7191e312.png)
![image](https://user-images.githubusercontent.com/62553416/186273378-8cf6e8f7-baa7-4f19-b167-78c188daba97.png)
![image](https://user-images.githubusercontent.com/62553416/186273398-6a7f6257-c2d7-4425-86ce-8e681498d10e.png)
![image](https://user-images.githubusercontent.com/62553416/186273569-3354b234-9432-4b19-9f7c-79d6b7d17343.png)

**Comment by peppinoita** [comment]
Remove the ifruit store map

**Comment by Flozii2** [comment]
Looks like it is a MLO problem, nothing to do with ipls.

**Comment by GameBoyNL** [comment]
I don't have a ifruit store map

**Comment by BaziForYou** [comment]
> Hello, i just noticed that outside Vangelico Jewel Store, the place has a hole and if you walk, you fall into void. And on the stair side you also fall through the void. ![image](https://user-images.githubusercontent.com/62553416/186273355-0118e996-140a-4c14-9230-871f7191e312.png) ![image](https://user-images.githubusercontent.com/62553416/186273378-8cf6e8f7-baa7-4f19-b167-78c188daba97.png) ![image](https://user-images.githubusercontent.com/62553416/186273398-6a7f6257-c2d7-4425-86ce-8e681498d10e.png) ![image](https://user-images.githubusercontent.com/62553416/186273569-3354b234-9432-4b19-9f7c-79d6b7d17343.png)

its not ipl never ipl edit normal ybns you have some maps have problem near there as i know i had one UJ map have this problem check your addon maps
