### ISSUE TITLE
Holes at Picture Perfect Drive

### ISSUE THREAD

**Issue by Royalstick** [Bob74/bob74_ipl#106]
Hole at ![hole](https://user-images.githubusercontent.com/93442609/188325071-a8afc639-68e1-4a40-b57c-7a2b531e950c.PNG), with GameBuild 2699 and GameBuild 2545 only

**Comment by benzon** [comment]
This is prop a MLO you got installed thats the issue here.

**Comment by BaziForYou** [comment]
> Hole at ![hole](https://user-images.githubusercontent.com/93442609/188325071-a8afc639-68e1-4a40-b57c-7a2b531e950c.PNG), with GameBuild 2699 and GameBuild 2545 only

check and no problem maybe have one addon map have conflict in there

**Comment by Royalstick** [comment]
I got no mlo right there. And nothing close, the most close mlo is at other side of the map. 
And it works good at previews version.

**Comment by coresync2k** [comment]
deactive all MLOS, look if it works ... if it works, it is a MLO
