### ISSUE TITLE
Luxury Auto Base IPL

### ISSUE THREAD

**Issue by Destrah** [Bob74/bob74_ipl#108]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes

**Describe the bug**
There are invisible walls at Luxury Autos interfering with our added MLO. I believe the latest GTA 5 update (The Criminal Enterprises) added an IPL to the game. Not sure what the IPL is called to disable it. This would be a great addition to this script to be able to disable it or have it unloaded by default.

I did revert back to game build 2612 and I was able to go in and out of our MLO just fine. So it is confirmed that there is an IPL that was added in the most recent update.

**To Reproduce**
x: -805.58, Y: -225.44, Z: 37.22

**Versions**
 - 2699
 - Cerulean

**Comment by Sinistermind81** [comment]
i have this same issue with my Luxury Auto, in game build 2699

**Comment by HysteriaRP** [comment]
Same with build 2699

**Comment by Avanae** [comment]
Did any of you found out what it was? I'm using LB Customs Sunshine Auto's and an invisible wall is blocking the entrance for me as well. I went through all the game files using the bh1_13_0 ybn but could not find any files aside from the old files.

**Comment by Avanae** [comment]
@HysteriaRP @Sinistermind81 @Destrah it turns out that b2699 added hei_ variants of the collisions used for the Rockford Sunrise Autos Dealership. All you need to do is copy and duplicate bh1_13_0.ybn and hi@bh1_13_0 and name them hei_bh1_13_0.ybn and hi@hei_bh1_13_0.ybn and it should work.

**Comment by DesertSnake0424** [comment]
I'm trying to remove the base luxury MLO but for some reason cant find it. Any help?

**Comment by alberttheprince** [comment]
> Rockford Sunrise Autos Dealership

So assuming the issues here were from another MLO not making changes for the new build, which I assume they've probably done 2 years later.

**Comment by gamer1997k** [comment]
if anyone is still having issue change this in the cfg 
set sv_enforceGameBuild security
