### ISSUE TITLE
franklin aunties ipl

### ISSUE THREAD

**Issue by C17DAGOAT** [Bob74/bob74_ipl#109]
hello i was wondering how i could stop the ipl from franklin aunties loading in

**Comment by Bob74** [comment]
Hi, by default it doesn't load an ipl (it ensures the room is empty):
```lua
LoadDefault = function()

    -- This is where it would load an ipl but "Style.empty" is an empty string
    FranklinAunt.Style.Set(FranklinAunt.Style.empty)

   -- Disabling props to make sure the room is empty
    FranklinAunt.Details.Enable(FranklinAunt.Details.bandana, false)
    FranklinAunt.Details.Enable(FranklinAunt.Details.bag, false)

    RefreshInterior(FranklinAunt.interiorId)
end
```

If for any reason you still want to avoid this code being executed, you can comment [client.lua line 13](https://github.com/Bob74/bob74_ipl/blob/master/client.lua#L13).
