### ISSUE TITLE
lasers dont work inside after hours night club .

### ISSUE THREAD

**Issue by driouach88** [Bob74/bob74_ipl#11]
hi there , first of all thanks for the amazing work man .i managed to make everything work in the night club such as monitors , spotlight peds the only thing im struggling with is the lasers . i just dont seam to find how its done . please let me know if u have an idea , all i need is a hint .thanks again

**Comment by Bob74** [comment]
Hi!
Did you try enabling laser lights?
```Lua
AfterHoursNightclubs.Interior.Lights.Lasers.Set(AfterHoursNightclubs.Interior.Lights.Lasers.yellow, true)
```
You'll find more lighting styles here: https://github.com/Bob74/bob74_ipl/wiki/After-Hours:-Nightclubs#lights

**Comment by driouach88** [comment]
i have no idea how i missed that . thank you so much man . people like are the ones who make a difference in fivem community . btw do u have any link for donations ? or patreon ?

**Comment by Bob74** [comment]
I didn't set up any donations, but thank you for thinking about it ^^

I really hope I will have time to update this resource, there is so much left to do.
