### ISSUE TITLE
Where can i find the Enable/Disable InteriorProp of CASINO? The full list

### ISSUE THREAD

**Issue by Gameadictive** [Bob74/bob74_ipl#113]
Well exactly that,

        EnableInteriorProp(penthouse, "set_pent_tint_shell")
	DisableInteriorProp(penthouse, "set_pent_bar_party_1")  
	DisableInteriorProp(penthouse, "set_pent_bar_party_2")
	DisableInteriorProp(penthouse, "set_pent_bar_party_after")
	EnableInteriorProp(penthouse, "set_pent_media_bar_open")
	
Where is the list? The wiki has no casino.

**Comment by Krislyz** [comment]
If you were talking about the penthouse props, all InteriorProps should be located [here](https://github.com/Bob74/bob74_ipl/wiki/Executives-&-Other-Criminals:-Penthouses).
If you were talking about the casino props, I don't know. Maybe [this](https://wiki.rage.mp/index.php?title=Interior_Props) might help.
