### ISSUE TITLE
Giant hole in map at Postal 6200

### ISSUE THREAD

**Issue by gigitygamer** [Bob74/bob74_ipl#116]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes

**Describe the bug**
Very large hole in map in middle of road that HAS COLLISIONS

**To Reproduce**
vector4(-1016.07, 387.99, 71.34, 33.49)

**Expected behavior**
The road is jsut invisible in this area

**Screenshots**
![image](https://user-images.githubusercontent.com/118565851/204674895-6f8898b4-3de7-4dff-bd6f-b5078864f81b.png)

**Versions**
 - Game build version-- 2699
 - Resource version -- most recent

**Comment by TugaPowerROM** [comment]
still no fix for this ?
