### ISSUE TITLE
Graphics bug

### ISSUE THREAD

**Issue by Melonnsc** [Bob74/bob74_ipl#118]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes

**Describe the bug**
After some time, and when you travel around the map the graphics get lost and you can just see no textures on objects, fall through map

**To Reproduce**
It happens everywhere no matter where you are

**Expected behavior**
Fix the holes of map and add some gta Online interiors

**Screenshots**
none

**Versions**
 - 6117
 - 2.1.1

**Comment by ItzCelyrian** [comment]
This is a well known FiveM Bug caused by Vehicles which stops the game from loading any textures from the location where you originally tried to load the correupted Vehicle.

**Nothing from bob74_ipl is causing this!**
