### ISSUE TITLE
bob74_ipl blocking Rockford PD interior

### ISSUE THREAD

**Issue by PC1up** [Bob74/bob74_ipl#119]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes

**Describe the bug**
So I've been using a Rockford PD custom interior for a while and decided to add bob74_ipl to just have all the default and dlc things. After restarting the server with bob74_ipl, the doors to the PD were blocked. I searched through the whole resource but couldnt find an IPL which blocks Rockford PD doors.

**To Reproduce**
Install Custom Rockford PD
Install bob74_ipl
Restart server
Try to walk into rockford pd

**Expected behavior**
I expected the ipls to block it, but I also expected me being able to disable the IPL which blocks the doors.

**Screenshots**
Not really possible, since it would only show me standing infront of a door

**Versions**
 - Game build version: 2699
 - Resource version: 2.1.1

**Comment by DigitalFire06** [comment]
This is an issue with on of the streamed .ybn files. If you go you your bob74_ipl folder than to stream you want to delete on file called hei_bh1_20_0.ybn. That file creates a static collision that is not allowing you to enter

**Comment by alberttheprince** [comment]
Seems like similar issue to https://github.com/Bob74/bob74_ipl/issues/108

Should probably reach out to the mlo dev (I assume this is fixed at this point).
