### ISSUE TITLE
Hole in the map

### ISSUE THREAD

**Issue by Smailas01** [Bob74/bob74_ipl#121]
Hello next to the North Rockford Drive road is the house and all the territory is a hole. POSTAL CODE: 832

Picture:
https://i.imgur.com/M3xUkBH.png

Versions:
Game version: 2699
Resource version: 2.1.1

**Comment by NeenGame** [comment]
I don't have this problem. Search if you have another ipl, mlo who is connected with this area

Versions:
Game version: 2699
Resource version: 2.1.2
