### ISSUE TITLE
Aircraft Carrier Bug with the LOD

### ISSUE THREAD

**Issue by Max3dsl** [Bob74/bob74_ipl#123]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes 

**Describe the bug**
The Problem is when I fly with an Plane to the Aircraft Carrier the LOD inside wont load. 

**To Reproduce**
Coordinates or map screenshot of the location.

**Expected behavior**
A clear and concise description of what you expected to happen, a screenshot from GTA Online if relevant is welcome.

**Screenshots**
![Screenshot 2023-02-05 022400](https://user-images.githubusercontent.com/113060482/216796889-7314314d-393a-48db-9444-b9955afe87b6.png)

**Versions**
 - Game build version 2802
 - Resource version Manifest

**Comment by Tinky124** [comment]
Same problem @Max3dsl

**Comment by TheIndra55** [comment]
Unable to repro, feel free to reopen.
