### ISSUE TITLE
Yacht Removal

### ISSUE THREAD

**Issue by CollapsedLegacy** [Bob74/bob74_ipl#127]
Hi,

Not so much an issue, just a question. How do I go at removing all the yachts in LS? I have tried to disable them but they still spawn. there's like 30 of them!

**Comment by riotxxyz** [comment]
Hi there @CollapsedLegacy you might have another Resource starting the yachts specifically Gabz-Yachts spawns all 30 yachts , in the config it tells u how to disable them
