### ISSUE TITLE
Anyone know how to open a door?

### ISSUE THREAD

**Issue by ZeProf2Code** [Bob74/bob74_ipl#13]
Hello, how to open the door located at (142.3157653086 -769.60913085938 242.15208435059)
![image](https://user-images.githubusercontent.com/32982428/58074843-81900e00-7ba6-11e9-9184-28ca52ee3c78.png)

**Comment by Bob74** [comment]
I suggest you ask on FiveM forums or since it is some map editing, directly on CodeWalker's Discord.
Besides editing the ymap file directly (and possibly the collision file), I have no idea how to open these doors.

I close the issue since it is not one related to the script.

**Comment by ZeProf2Code** [comment]
Sometimes,it is open idk why but I can't enter it even when it's opened I need to noclip into it and when I noclip into it, I don't fall in the void it's a real interior

**Comment by Bob74** [comment]
I still can't edit the door itself, but removing the collisions works when the door appears opened:
![image](https://user-images.githubusercontent.com/9498543/58115427-4d463d00-7bfa-11e9-9461-e4fbca132f63.png)

I see in CodeWalker that the door has some extensions and most importantly, it has:
`startsLocked = 1`

I'm quite sure that if we can edit the way the door is spawned, we could make it a classic working door.

**Comment by ZeProf2Code** [comment]
you know how to do it?

**Comment by Bob74** [comment]
I'm not able to edit the door yet.
I'm looking at it but I don't know if I will find how.
