### ISSUE TITLE
deactivate ipl in another script

### ISSUE THREAD

**Issue by alexwilliamlex** [Bob74/bob74_ipl#134]
Hello,
I'm using the latest version of bob74_ipl
I'm using the windows 7290 artifact.

I've created a custom_ipl script in which I've put a fxmanifest that loads client-side test_client.lua
I put in this : 

```
Citizen.CreateThread(function()
    HLApartment1 = exports['bob74_ipl']:GetHLApartment1Object()
    HLApartment2 = exports['bob74_ipl']:GetHLApartment2Object()
    HLApartment3 = exports['bob74_ipl']:GetHLApartment3Object()
    HLApartment4 = exports['bob74_ipl']:GetHLApartment4Object()
    HLApartment5 = exports['bob74_ipl']:GetHLApartment5Object()
    HLApartment6 = exports['bob74_ipl']:GetHLApartment6Object()
    GunrunningYacht = exports['bob74_ipl']:GetGunrunningYachtObject()
    HLApartment1.Ipl.Interior.Remove()
    HLApartment2.Ipl.Interior.Remove()
    HLApartment3.Ipl.Interior.Remove()
    HLApartment4.Ipl.Interior.Remove()
    HLApartment5.Ipl.Interior.Remove()
    HLApartment6.Ipl.Interior.Remove()
    HLApartment7.Ipl.Interior.Remove()
    GunrunningYacht.Enable(false)
end)
```

I'm trying to figure out how to disable some apartments and the yacht with bob74_ipl.

Have a nice day! 

[custom_ipl.zip](https://github.com/Bob74/bob74_ipl/files/14895372/custom_ipl.zip)

**Comment by TheIndra55** [comment]
This code should work, especially for the yacht. Not sure if you can easily remove the interiors since they are already always stramed.

**Comment by alexwilliamlex** [comment]
Hello @TheIndra55 
Unfortunately, even the yoat doesn't work. I haven't touched bob74_ipl, maybe I need to add something to it?

**Comment by TheIndra55** [comment]
Code works for me, are you sure you are looking at the right yacht and not running the code too early?

**Comment by alexwilliamlex** [comment]
So apparently it works, but not on all IPLs. Like apartments, I don't really understand

**Comment by TheIndra55** [comment]
The interiors are already loaded by the game, so you can't request or unload them. Honestly unsure why that method even exists.
