### ISSUE TITLE
 Invisible border around Gabz PDM

### ISSUE THREAD

**Issue by thefurrycanadian** [Bob74/bob74_ipl#135]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Its no longer there
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes, b7827

**Describe the bug**
There is an invisible border around Gabz PDM. I believe its because of the new Simon fix for the Criminal Enterprise DLC. I created a client script showing:
```
   Simeon = exports['bob74_ipl']:GetSimeonObject()
    Simeon2 = exports['bob74_ipl']:CriminalEnterpriseSmeonFix()

    Simeon.Ipl.Interior.Remove()
    Simeon.Enable(false)
    Simeon2.Ipl.Interior.Remove()
    Simeon2.Enable(false)
    
    RefreshInterior(Simeon.interiorId)
    RefreshInterior(Simeon2.interiorId)
```
and its still there. The WIKI is not up to date to show new DLC also.

**To Reproduce**
Head to Simons PDM, well Gabz PDM is added

**Expected behavior**
To be able to walk through the doors of PDM

**Versions**
 - Game build version: b7827
 - Resource version: 2.1.4

**Comment by Bossman02** [comment]
its the file `dlc_mercenaries/base.lua`, i have also the same problem and in gabz's discord one user said without loading that file it works ok and i have confirmed it's true, so it's and issue when your gamebuild is 2944 or higher

**Comment by TheIndra55** [comment]
> its the file `dlc_mercenaries/base.lua`, i have also the same problem and in gabz's discord one user said without loading that file it works ok and i have confirmed it's true, so it's and issue when your gamebuild is 2944 or higher

This is useful info, I wasn't aware this fix would cause any issues so I didn't make it configurable.

I'm currently working on updating the documentation, and will also make sure to make these fixes configurable in the next version.

**Comment by TheIndra55** [comment]
Please try the latest release with

```lua
MercenariesFixes = exports['bob74_ipl']:GetMercenariesFixesObject()

MercenariesFixes.Enable(false)
```
