### ISSUE TITLE
fall through map between Ace Jones Drive and Kortz Drive

### ISSUE THREAD

**Issue by NinaRatchett** [Bob74/bob74_ipl#136]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes

**Describe the bug**
We fall through map between Ace Jones Drive and Kortz Drive at the house with the tennis court on the front lawn.

**To Reproduce**
Coordinates or map screenshot of the location.
vector4(-1968.91, 480.1223, 103.7505, 288.6874)
vector4(-1968.424, 457.2921, 103.1394, 294.908)

**Expected behavior**
A clear and concise description of what you expected to happen, a screenshot from GTA Online if relevant is welcome.
When we walk on the grass or near the house we fall through the  map and then if you fall all the way it puts you back in the street in the same area. 

**Screenshots**
![holeinmap](https://github.com/Bob74/bob74_ipl/assets/144497083/b987160b-ef16-481e-a36e-e2e226b1addf)

**Versions**
 - Game build version 2545
 - Resource version 2.2.0 and 2.1.1

**Comment by TheIndra55** [comment]
Since I cannot reproduce this on an empty server base it would be helpful to know which map modifications your server has.

**Comment by NinaRatchett** [comment]
> Since I cannot reproduce this on an empty server base it would be helpful to know which map modifications your server has.

My bad it was a separate issue
