### ISSUE TITLE
Conflit with GABZ

### ISSUE THREAD

**Issue by Charles11130** [Bob74/bob74_ipl#137]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes

**Describe the bug**
Hello, I have a conflict with the PDM of Gabz and the casemate hospital.
![pdm](https://github.com/Bob74/bob74_ipl/assets/168089975/13fc7671-bae3-4dff-a3c2-f987d5221dc8)
![pill](https://github.com/Bob74/bob74_ipl/assets/168089975/4da0498b-8d9f-426c-8be9-5de3bce5bc86)

**To Reproduce**
Coordinates or map screenshot of the location.

**Expected behavior**
A clear and concise description of what you expected to happen, a screenshot from GTA Online if relevant is welcome.

**Screenshots**

**Versions**
 3095
 - Resource version

**Comment by TheIndra55** [comment]
Please try disabling the fixes added in 2944:
```lua
MercenariesFixes = exports['bob74_ipl']:GetMercenariesFixesObject()

MercenariesFixes.Enable(false)
```

**Comment by SubwooferNL** [comment]
not fixing the issue ?
have disabled the mercenaries fixes but still see the airco boxes in the garage door and the glitch in the pillbox garage
i have nothing else running what can cause this problem

**Comment by SubwooferNL** [comment]
> not fixing the issue ? have disabled the mercenaries fixes but still see the airco boxes in the garage door and the glitch in the pillbox garage i have nothing else running what can cause this problem

well i have fixed the pdm with the 2 boxes only the garage from pillbox not

**Comment by 00Chaotic** [comment]
@SubwooferNL how did you fix the PDM issue?

**Comment by alberttheprince** [comment]
There are fixes for these in the gabz Discord I think.
