### ISSUE TITLE
CAN YOU MAKE IT SO YOU CAN DISABLE MAZE BANK ARENA

### ISSUE THREAD

**Issue by vhypno** [Bob74/bob74_ipl#138]
so when i go off the aircraft carrier i blow up because of where the maze bank arena interior is placed. can you make it so it can be disabled? also with the openinteriors mod that goes with the aircraft carrier, I thought your mod would include the interior but when I turn off the openinterior mod it doesn't load

**Comment by vhypno** [comment]
how?

**Comment by TheIndra55** [comment]
The maze bank arena interior above the sea is not loaded by bob74_ipl, check your other resources
