### ISSUE TITLE
Confliction with GABZ PDM and Simon's shop

### ISSUE THREAD

**Issue by KremitForg** [Bob74/bob74_ipl#139]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes

**Describe the bug**
The original collisions are still present when the ipl is active. Because of this, there is an invisible barrier around GABZ PDM and you are unable to enter though "normal" means.

**To Reproduce**
-48.1 -1105.69 27.26

**Expected behavior**
There should be no barrier around the mlo

**Screenshots**

**Versions**
 - 3095
 - 2.2.1

**Comment by KeepItLokiTho** [comment]
comment out "Simeon.LoadDefault()" and restart bob74_ipl and the barrier will go away. leaving the ipl active will cause issues.

**Comment by Benji404-AU** [comment]
any fix for this

**Comment by Benji404-AU** [comment]
Nah that still didnt work,

**Comment by NeaKus** [comment]
I have same issue

**Comment by Benji404-AU** [comment]
yeah i am debugging it now, seeing what IPL is making it do it the, update before this its just simons but now a diffent ipl is making that issue

**Comment by NeaKus** [comment]
https://github.com/Bob74/bob74_ipl/issues/135
this helps
`MercenariesFixes = exports['bob74_ipl']:GetMercenariesFixesObject()

MercenariesFixes.Enable(false)`

**Comment by Benji404-AU** [comment]
Okay what i did was 

in fxmanifest 
--, "gta_mpsum2/simeonfix.lua"
same with simon.lua

working fine now

**Comment by TheIndra55** [comment]
Ideally the creator of the map would make it compatible with these new IPLs, since the fixes IPL contains other map fixes too.

**Comment by TrAsKiN** [comment]
Gabz is usually pretty reactive on this. Check [Keymaster](https://keymaster.fivem.net/asset-grants) to see if these assets have been updated.
