### ISSUE TITLE
Problem level -1 Pillbox Gabz

### ISSUE THREAD

**Issue by SerafinXIV** [Bob74/bob74_ipl#143]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server ? Yes

**Describe the bug**
Small problem with level -1 of Gabz's Pillbox, there seems to be "residues" of the original setting, they appear at a certain angle and disappear at times. But even when they disappear, we collide with some.
For information the line in config.lua is : "PillboxHospital.Enable(false)"
If you have any idea what the problem is, I would be very grateful. Thank you in advance.

**To Reproduce**
vector3(354.11, -589.12, 28.8)

**Screenshots**
![pillbox](https://github.com/Bob74/bob74_ipl/assets/172977175/989a49c6-2c5e-406b-b7e6-94843d18f033)
![pillbox garage](https://github.com/Bob74/bob74_ipl/assets/172977175/f3233c9b-1169-4be5-b625-ad9ac84fb57a)

**Versions**
 - Game build version 7290 (latest recommended)
 - Resource version 2.2.1

**Comment by NickReagan** [comment]
You need to go into the client.lua and set PillboxHospital.Enable(true) to false.
`lua
    -- Pillbox hospital: 307.1680, -590.807, 43.280
    PillboxHospital.Enable(false)
`

**Comment by SerafinXIV** [comment]
Hello, thank you for your answer but this is already the case, the line is already on "false" and despite this the problem persists.

**Comment by WolfTM** [comment]
> Hello, thank you for your answer but this is already the case, the line is already on "false" and despite this the problem persists.

Cleared server cache?

**Comment by SerafinXIV** [comment]
Already done too. :-(

**Comment by SerafinXIV** [comment]
Thank you for your reply.
So if I understood your instruction correctly, here is the screenshot of what we modified in the "client.lua" but unfortunately still the same.

![Capture d'écran 2024-07-09 170912](https://github.com/Bob74/bob74_ipl/assets/172977175/872b7c8e-f4f9-41ee-b81e-264659d3fe20)

**Comment by JSON-135** [comment]
I am also having this same exact issue and its been driving me insane. And i have tried all of the above.
I also do not have any other files in relation to pillbox mlo except gabz, and bobsipl.

**Comment by alberttheprince** [comment]
This probably will never be fixed as gabz has abandoned working on their maps.

**Comment by TheIndra55** [comment]
This doesn't seem like an issue caused by bob74_ipl, but rather an addon map conflicting with the default interior. As mentioned in this issue you can disable the default interior by editing `client.lua` or disabling it from another resource, you can tell the author of the map to add this line to their resource to fix it.

**Comment by JSON-135** [comment]
i found out the issue was due to a legion parkinglot script that removes the barriers that don't go up and down.
