### ISSUE TITLE
Removal of the Luxury motorsport mlo

### ISSUE THREAD

**Issue by DesertSnake0424** [Bob74/bob74_ipl#144]
I know it is a base mlo and I have a  gym script and mlo that goes in place of the luxury auto spot but I cant figure out where to remove it so it is clashing once I enter the doors

**Comment by AdrianoGama** [comment]
comment out "Simeon.LoadDefault()" Clear the server cache and restart bob74_ipl and the barrier will go away. leaving the ipl active will cause issues.
