### ISSUE TITLE
Different names in the dlc_finance offices

### ISSUE THREAD

**Issue by LenaMatoi** [Bob74/bob74_ipl#146]
I need to put a different name in each office, currently I can only put this code in one office:

Citizen.CreateThread(function()
    FinanceOrganization = exports['bob74_ipl']:GetFinanceOrganizationObject()

    -- Setting the name parameters
    FinanceOrganization.Name.Set("BUFETE DE ABOGADOS DE LOS SANTOS", FinanceOrganization.Name.Style.normal, FinanceOrganization.Name.Colors.black, FinanceOrganization.Name.Fonts.font1)

    -- Enabling the name to be able to see it
    FinanceOrganization.Office.Enable(true)
end)

Since the same name continues to appear in the others, I don't know how to make each office have its own name.

**Comment by Bob74** [comment]
Unfortunately, this is the way GTA V works. You cannot set the name one time for all, you have to set the correct name when the player enters the office.

**Comment by LenaMatoi** [comment]
So I can't give the arcadius one name and the mazebank another name?

**Comment by Bob74** [comment]
You can, but don't think of it as different organizations. The game renders only one organization for the current player.
The organizations is actually linked to the player and not the office. So you will have to chose what to display to the player depending where they are.

You have to set the correct organization name when the player enters the office.
You certainly teleport the player into the office, this is where you need to put the code that will set the correct name of the organization depending where you teleport the player.

In GTA:O, multiple players can have different organizations in the same office at the same time. So what Rockstar does is detect what organization you are going to see and what players will be hidden or shown depending of your choice when asking to enter the building.

You may not want to replicate this system exactly. If on your server only one organisation can have an office, you won't have to hide/show the players. But you still have to the tell the player client what organization they are going to see in the office.
