### ISSUE TITLE
If i near the Prison texture are missing

### ISSUE THREAD

**Issue by goldbergbaba** [Bob74/bob74_ipl#150]
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes

If i near the prison in gta the ground is starting the texture missing

![image](https://github.com/user-attachments/assets/3b4f6b93-e5a7-4102-bcf4-93debc870476)
![image](https://github.com/user-attachments/assets/5556b098-9f43-402b-84e9-a18e77f66be3)
![image](https://github.com/user-attachments/assets/22fa02ed-9bbb-4d67-8127-742e491d87fb)

can someone help me maybe?

**Comment by alberttheprince** [comment]
Pretty sure this is something related to the newest build of FiveM. Been increasing reports of this issue.

https://forum.cfx.re/t/lod-slod-texture-issues/5074672
