### ISSUE TITLE
Grapeseed's farm

### ISSUE THREAD

**Issue by Anubis7o5** [Bob74/bob74_ipl#154]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes b9655

**Describe the bug**
if you go into the Farmhouse you fall through the map

**To Reproduce**
coords: 2447.9, 4973.4, 47.7

**Screenshots**
![farmhouse](https://github.com/user-attachments/assets/3f99f3da-8cea-46c6-a2a7-61598bd98ba7)

**Versions**
 - Game build version: 3258
 - Resource version: 2.3.2

**Comment by TheIndra55** [comment]
Unable to reproduce this, did you mean above that the issue still happens without bob74_ipl? Do you have any other maps?

**Comment by Anubis7o5** [comment]
without bob74_ipl there is no Building only a great hole
