### ISSUE TITLE
Cartel Garage Interiour won´t show up.

### ISSUE THREAD

**Issue by LettyR** [Bob74/bob74_ipl#159]
[](url)**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there?  -> Yes
Did you use the latest version of `bob74_ipl` ?  -> Yes
Did you use an up to date server [artifact] -> Yes -> [10367] -> Gamebuild 3095

**Describe the bug**
The Interiour in the Cartel Garage was 2 days there, now it´s completly gone.I try everything to show it up, but it doesn´t work.

**Screenshots**

![Screenshot_83](https://github.com/user-attachments/assets/807b4c02-728c-4e66-b2ef-dd86801b56df)
![Screenshot_84](https://github.com/user-attachments/assets/b8d0c190-8f3f-401a-b872-dc64ef1f7e8f)
![Screenshot_85](https://github.com/user-attachments/assets/92406361-348d-4ed8-9ccf-e0ffa2cb7b42)
![Screenshot_86](https://github.com/user-attachments/assets/36fe2d56-a4bf-400e-9719-87a4858ab6ab)
![Screenshot_87](https://github.com/user-attachments/assets/f84edd9b-ed40-4154-b2a8-9a776b39e7e5)

Maybe someone is able to tell me, how to do changes in the cartel_garage.lua ? 
I had no clue about IPLs ... 
![Screenshot_1](https://github.com/user-attachments/assets/d3760260-c173-46e1-b807-ca21939b0e4f)

Thank you !

**Comment by TheIndra55** [comment]
Cannot reproduce, do you have any other resources which stream this interior?

**Comment by LettyR** [comment]
Nope, also no other Mappings nearby.
The next one is the Car Meet Interiour.
But i followed the hint and disable all Mappings.
The Interieur is still missing.
