### ISSUE TITLE
FIB Comm Room

### ISSUE THREAD

**Issue by lfuelling** [Bob74/bob74_ipl#17]
Hi,

right now, the Comm Room in the FIB top floor is some sort of smaller office and not the one shown in the mission.

I wonder if it's possible to replace that with the interior used in the mission where Michael hacks the FIB, since the bigger room looks more impressive.

**Comment by Bob74** [comment]
Hi,

I'm not sure I understand which room you're talking about.
Is that this [one](https://youtu.be/YFV9HoUSorM?t=417)?

Because it seems to be the same in game:
![fib1](https://i.imgur.com/7ks3Akm.jpg)
![fib1](https://i.imgur.com/Wtm64Ck.jpg)
![fib1](https://i.imgur.com/ZNgPrym.jpg)

**Comment by lfuelling** [comment]
Sorry, you're right. I guess the mission cutscene made it look bigger.
