### ISSUE TITLE
Bahama Mama's Error

### ISSUE THREAD

**Issue by itismejoey** [Bob74/bob74_ipl#19]
client.lua line 26: attempt to index a nil value (global 'BahamaMamas')

**Comment by Bob74** [comment]
Seems like the file `bob74_ipl\gtav\bahama.lua` is missing from your resource.
Reinstall the resource.

**Comment by itismejoey** [comment]
[![Screenshot from Gyazo](https://gyazo.com/1a5676cfde582bd74b72ffef467e42de/raw)](https://gyazo.com/1a5676cfde582bd74b72ffef467e42de)
Nope, that file is there.

**Comment by Bob74** [comment]
What version is your `__resource.lua` file?
```Lua
-- =========================================================
--               Load and customize your map.               
-- ---------------------------------------------------------
--
-- Author: Bob_74
-- Version: 2.0.8
-- 
-- Resources:
-- **********
-- IPL list:			https://wiki.gt-mp.net/index.php/Online_Interiors_and_locations
-- Props list:			https://wiki.gt-mp.net/index.php/InteriorPropList
-- Interior ID list : 	https://wiki.gt-mp.net/index.php/InteriorIDList
--
```

**Comment by itismejoey** [comment]
Yep, matches above.

I also posted an issue here as well: https://forum.fivem.net/t/release-v2-fix-holes-in-the-map-up-to-after-hours/25240/520?u=itismejoey

**Comment by Bob74** [comment]
I just retried and everything works great.
Did you entirely remove the previous resource and install the new one in place?
Have you tried removing the `cache` folder from the server?

**Comment by itismejoey** [comment]
Yeah, I'll give that a shot. It was doing some testing after being up all night.

**Comment by itismejoey** [comment]
I'm gonna go with it being a cache issue, because everything is working now. Thanks!
