### ISSUE TITLE
Biker Clubhouse flashing Walls and Murals

### ISSUE THREAD

**Issue by starr0stealer** [Bob74/bob74_ipl#20]
The default settings for Biker Clubhouse 1 & 2 results in the walls flashing between each version. I also found that with at least Clubhouse 1 you couldn't change the mural or decorations, without resulting in an overlap of each set.

After doing some debugging I found that each Clubhouse has default values set (not yours). For example if you just have (in your files):

```
    LoadDefault = function()
        BikerClubhouse1.Ipl.Interior.Load()
 
        RefreshInterior(BikerClubhouse1.interiorId)
    end
```

Will result in Walls, Furniture, & Decoration set to v2, Meth, Cash, Coke, Weed, Counterfeit, & Documents to just stash 3, and mural set to route 68.

Regardless of what settings are done in your files (or ours), the defaults don't clear. This is because `IsInteriorPropEnabled` returns false until enough time has passed after `RefreshInterior` (maybe after `RequestIpl`).

In the case of Clubhouse 1, I was able to get around this by explicitly calling `DisableInteriorProp` on the values I didn't want. But Clubhouse 2 was a little more tricky, due to some reason using Walls v1 (bricks) wouldn't still retain the Walls v2 (plain, multi color) as well as the clutter in the Mod Booth.

So other workarounds I found was to call `restart bob74_ipl`, and removing the if condition and always disable [here @ common.lua L96](https://github.com/Bob74/bob74_ipl/blob/2.0.8/lib/common.lua#L96)

**Comment by Bob74** [comment]
Are you sure you're not using another resource using `bob74_ipl`? And not putting your code to interact with the interiors inside a loop?

I've just checked and the clubhouses are fine, I can also set decoration and mural of each.
