### ISSUE TITLE
Vangelico hole

### ISSUE THREAD

**Issue by Ex0r** [Bob74/bob74_ipl#21]
There's a large hole near vangelicos that causes you to fall through the map.

**Comment by Bob74** [comment]
Where?
![image](https://user-images.githubusercontent.com/9498543/70931897-c561cd80-2038-11ea-8067-4bf6b7b270f2.png)
![image](https://user-images.githubusercontent.com/9498543/70931913-cc88db80-2038-11ea-9b5f-5554e5f8eca8.png)

**Comment by Ex0r** [comment]
On the west side of the alleyway near the steps. Even locals fall through.

**Comment by Ex0r** [comment]
With the default provided ipl unloaded the hole isn't there so I'm sure it's related to the jewelry store ipl.

**Comment by Bob74** [comment]
Is it this place?
![image](https://user-images.githubusercontent.com/9498543/70932291-ae6fab00-2039-11ea-9ae6-6ef5a09933d0.png)

It can be a conflict with another resource but I'm only using my resource to test and it works fine.

**Comment by Ex0r** [comment]
Yes that's the place. We don't have any resources other than yours that
deal with maps and whenever we walk around in that area we fall through.

**Comment by Bob74** [comment]
Did you try disabling some of your resources to find which one might conflict?

**Comment by Ex0r** [comment]
Can you verify which IPL is the correct one to be loaded? Maybe somebody else configured the wrong one.

**Comment by Ex0r** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/1313503/70932937-dd215d80-2008-11ea-93aa-d5a9d55db32f.png)

This is the cut off. Once we go past this spot there is no collision and we fall through the map.

**Comment by Bob74** [comment]
The only IPL I load in this area are these ones:
```Lua
    RequestIpl("post_hiest_unload") -- Jewelry
    RequestIpl("refit_unload") -- Max Renda
```

You can try removing them manually to see if it does something:
```Lua
    RemoveIpl("post_hiest_unload") -- Jewelry
    RemoveIpl("refit_unload") -- Max Renda
```

Also, I'm interested in your resources list if you don't mind.

**Comment by Ex0r** [comment]
Okay interesting. Removing them doesn't appear to be affecting the hole so it must be something else. All of the maps we load are on the east side of the map. Looks like it's not the IPL loader after all! Guess I've got some investigation to do.

**Comment by Bob74** [comment]
I suggest you try without loading any other maps since it can use quite a lot of memory and lead to this kind of issue (if it is custom ymap).

I'm really interested if you find out which resource cause this since it seems to be quite common ;)

**Comment by Ex0r** [comment]
So I found the issue in my particular case. I am using a custom map thst opens a couple magazine shops in town, which conflict with the vangelico map for some reason.

**Comment by Bob74** [comment]
Thanks, I think most people having these issues use custom maps also.
Good to know 😉
