### ISSUE TITLE
accidental find of one of the warehouses

### ISSUE THREAD

**Issue by Sigma-Erebus** [Bob74/bob74_ipl#26]
this is not really an issue, but as i personally do not know how to exactly code the ipl's and such, i thought i'd post my find here. but after moving a bit in noclip in my fivem server, i found one of the warehouses (the large one). seen as they are currently on the to-do list, i'd provide you the coords i found this at:
998.40240478516,-3099.6997070313,-38.999900817871
personally i have no clue how it got there, because i didn't modify your code at all (well, except the config obviously), but other than that i don't really know. next to this mod, i also have ipl loader installed, which might have something to do with the find: https://github.com/ESX-PUBLIC/fivem-ipl
i hope this might help with adding the warehouses.
![largewarehouse](https://user-images.githubusercontent.com/65902131/82812196-c245f580-9e92-11ea-87b8-5035b734dfee.PNG)

EDIT:
curiosity got to me, and i went looking around, here's the medium one:
1050.0114746094,-3105.3037109375,-38.999954223633
![mediumwarehouse](https://user-images.githubusercontent.com/65902131/82812521-75165380-9e93-11ea-979e-e06067fb388f.PNG)

and the small one:
1089.6859130859,-3101.123046875,-38.999961853027
![smallwarehouse](https://user-images.githubusercontent.com/65902131/82812606-a55df200-9e93-11ea-9764-03612760b074.PNG)

**Comment by Bob74** [comment]
I wanted to add full usage of the warehouses (adding crates of goods and such) so I didn't implemented it.
But I guess it's kinda stupid, it would be better to get empty warehouses than nothing :) 

I'm gonna add it.

**Comment by Bob74** [comment]
https://github.com/Bob74/bob74_ipl/wiki/Finance-&-Felony:-Warehouses

**Comment by Sigma-Erebus** [comment]
I see, it makes sense that you'd want the ability to fill them first.
And by the way, I found some other things as well. which you might want to add as well.
i found these in another thread, so credit goes to Smallo, but i thought i'd let you know.
https://forum.cfx.re/t/dev-doomsday-smugglers-run-interiors-props-ipls-teleport/92124
the first is a rather specific one, the missile silo from the doomsday heists finale:
1257.6689453125,4804.8403320313,-39.32861328125 (entrance of tunnel)
the problem with this one is that collision loads, but meshes and textures don't, the fix i found for this is to teleport in from the tunnel where you'd need to go in the online heist itself, i'd guess rockstar put this in as some kind of safeguard to prevent accidental entry in online or something like that, but i can't say for sure. all i know is that it works when done this way.
![image](https://user-images.githubusercontent.com/65902131/83071404-5a97d200-a06d-11ea-8de7-7e7ff7e807db.png)
![image](https://user-images.githubusercontent.com/65902131/83071471-78653700-a06d-11ea-97d2-46c1ae1ecaff.png)
![image](https://user-images.githubusercontent.com/65902131/83071730-e14caf00-a06d-11ea-826c-062959421ac8.png)
![image](https://user-images.githubusercontent.com/65902131/83071880-1953f200-a06e-11ea-92cd-b5b85f9dc5b2.png)
![image](https://user-images.githubusercontent.com/65902131/83072000-4d2f1780-a06e-11ea-8aa8-db778833d5c3.png)
the second is the IAA facility, located at:
2154.9655761719,2921.0466308594,-61.902481079102
![image](https://user-images.githubusercontent.com/65902131/83072167-967f6700-a06e-11ea-8686-ab000be77b67.png)
![image](https://user-images.githubusercontent.com/65902131/83072258-ba42ad00-a06e-11ea-8222-0f01b2ad4f60.png)
third is the server facility, located at:
2154.8049316406,2921.1110839844,-81.07551574707
![image](https://user-images.githubusercontent.com/65902131/83072372-f249f000-a06e-11ea-80de-f22d6a54ead4.png)
fourth is the bogdan submarine, located at:
514.30767822266,4887.880859375,-62.589931488037
![image](https://user-images.githubusercontent.com/65902131/83072642-6ab0b100-a06f-11ea-8683-8b1dbca21243.png)
and lastly, some house i accidentally teleported into when meaning to teleport to the entrance of my nightclub near mission row, i don't know if this is already added or not, but i thought i'd include it nonetheless:
346.60076904297,-1002.0798339844,-99.196197509766
![image](https://user-images.githubusercontent.com/65902131/83072810-b4010080-a06f-11ea-90f3-c57a3bd0f911.png)

i hope this helped, at least a bit, in improving the resource, keep up the good work!
