### ISSUE TITLE
Vangelico - Outside area has hole.

### ISSUE THREAD

**Issue by Nosmakos97** [Bob74/bob74_ipl#28]
Hello, i just noticed that outside Vangelico Jewel Store, the place has a hole and if you walk, you fall into void.

![image](https://user-images.githubusercontent.com/61381502/83534717-de344180-a4f9-11ea-872e-80d42e4c5089.png)

**Comment by Bob74** [comment]
Hi!

I don't get it, what is supposed to be there?

I checked inside CodeWalker and there is nothing too:
![image](https://user-images.githubusercontent.com/9498543/83550951-ee531d80-a507-11ea-9ac6-7f74c67aea54.png)

**Comment by Nosmakos97** [comment]
Seems like it was an interior of mine that caused this, i found the correct person and fixed the file.

**Comment by Bob74** [comment]
Ok so no pb here ^^

**Comment by Nosmakos97** [comment]
Yes we all good! Have a lovely day.
