### ISSUE TITLE
Counterfeit cash factory

### ISSUE THREAD

**Issue by Flameshocker** [Bob74/bob74_ipl#3]
I can't get the printers and the money on the table to spawn in i have tried everything but i can't get it to work  so if you could help me out i would be happy

![ladda ned 1](https://user-images.githubusercontent.com/25096682/50182270-962a5a80-0317-11e9-8acc-0af7fc981eef.png)
![ladda ned 2](https://user-images.githubusercontent.com/25096682/50182276-99bde180-0317-11e9-9de3-6b4d71b5bd25.png)

**Comment by Bob74** [comment]
You're right, I messed up on some values when I renamed the main object...
Hopefully it is fixed now on GitHub.

Thank you for reporting this!

**Comment by Flameshocker** [comment]
Well that solved it!. well no problem thanks for solving it so quik
