### ISSUE TITLE
O'Neil Farms Interior

### ISSUE THREAD

**Issue by ItsSimko** [Bob74/bob74_ipl#33]
I do not know if this is just me but when I try to go inside of the O'Neil farms i go to the door and it opens but I am blocked by a invisible door...

**Comment by rhapidfyre** [comment]
You may have another mod that modifies the interior files of this home. I use bob's and it works fine for me. If another mod affects the same ytr/ymap/etc file that this mod uses, it will cause unintended behaviors.
