### ISSUE TITLE
FiveM Update - High resource tick

### ISSUE THREAD

**Issue by MrWhitee4** [Bob74/bob74_ipl#34]
Hello,

I have the problem that in /lib/observers/InteriorIdObserver.lua between line [5,,50] there is a high resource tick of round about 2% going on the entire time. This occured with the latest FiveM Update. I used the profiler to identify the problem.

![image](https://user-images.githubusercontent.com/20826721/98147227-86489f00-1ecc-11eb-8c03-841b9f73ec41.png)

**Comment by manzarek123** [comment]
Change local _scanDelay = 0 to local _scanDelay = 500
in interiorIdObserver.lua

**Comment by MrWhitee4** [comment]
Thanks man it fixed the problem.
