### ISSUE TITLE
Bug apartments

### ISSUE THREAD

**Issue by Palacios06** [Bob74/bob74_ipl#38]
Hello, how about I have been trying for days to make the apartments work since they do not load well or I do not know what happens
thnaks
![unknown](https://user-images.githubusercontent.com/63920145/108756079-acdb2600-750d-11eb-9c45-06657484c17f.png)

**Comment by randogaming6252** [comment]
he hasnt been active for nearly 2 years, if github is correct. unfortunately you may be sol.

**Comment by Bob74** [comment]
Did you try removing resources that could conflict with this one?
