### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by xnubil** [Bob74/bob74_ipl#4]
https://github.com/Bob74/bob74_ipl/blob/6c9fe602a58594522c725cc0a6ea92ff1559d160/dlc_bikers/clubhouse1.lua#L4

The export in Wiki doesn't match the Export in Client code.

GetBikerClubhouse1Object
GetBikerBikerClubhouse1Object

**Comment by Bob74** [comment]
You're right, there is a mistake!

I fixed it in `bob74_ipl/dlc_bikers/clubhouse1.lua`.
Of course the right name of the export is `GetBikerClubhouse1Object`.

Thanks!
