### ISSUE TITLE
Prop issue

### ISSUE THREAD

**Issue by FakeItalianMan** [Bob74/bob74_ipl#43]
Hello I am trying to add the extra props that you show in your wiki into the CEO offices but it is not working. Can anyone explain to me what exactly I have to do to enable like the piles of money and such? Thanks.

**Comment by Bob74** [comment]
Hi, you need to create a new resource that will enable props and stuff.

As https://github.com/Bob74/bob74_ipl/wiki/How-to-interact-with-an-interior%3F:
- Create a new folder in your fiveM `resources` folder (let's say `myNewResource`)
- Inside the folder, create the file `fxmanifest.lua` according to the Wiki example:
```
fx_version 'cerulean'
games { 'gta5' }

author 'Me'
description 'Customize interiors'
version '1.0.0'

dependency 'bob74_ipl'

client_script "client.lua"
```
- Still inside the folder, create a file named `client.lua` that will contains the interiors customizations. Example:
```lua
Citizen.CreateThread(function()
    -- Getting the object to interact with
    FinanceOffice1 = exports['bob74_ipl']:GetFinanceOffice1Object()

    -- Enable maximum cash + Refresh interior to apply changes (using `true` as 2nd parameter)
    FinanceOffice1.Swag.Enable(FinanceOffice1.Swag.Cash, true)
end)
```
- Add your new resource to the server config file:
```
ensure bob74_ipl
ensure myNewResource
```
- It should do the trick

This example covers Office n°1 (Arcadius Business Centre), you can interact with other offices using these:
```lua
FinanceOffice1 = exports['bob74_ipl']:GetFinanceOffice1Object()
FinanceOffice2 = exports['bob74_ipl']:GetFinanceOffice2Object()
FinanceOffice3 = exports['bob74_ipl']:GetFinanceOffice3Object()
FinanceOffice4 = exports['bob74_ipl']:GetFinanceOffice4Object()
```

I hope it is clear enough.

------

Other examples:
```lua
-- Adding drug bags
-- They are divided in 3 parts (A, B and C):
FinanceOffice1.Swag.Enable(FinanceOffice1.Swag.DrugBags.A, true) -- Enable A
FinanceOffice1.Swag.Enable(FinanceOffice1.Swag.DrugBags.B, true) -- Enable B
FinanceOffice1.Swag.Enable(FinanceOffice1.Swag.DrugBags.C, true, true) -- Enable C + Refreshing interior (last `true` parameter)

-- Note: these 3 lines can be written in 1 single line:
FinanceOffice1.Swag.Enable(FinanceOffice1.Swag.DrugBags, true, true)
```

```lua
-- Open safe doors:
FinanceOffice1.Safe.Open("left")
FinanceOffice1.Safe.Open("right")
```

```lua
-- Add chairs at desks:
FinanceOffice1.Chairs.Set(FinanceOffice1.Chairs.on, true)
```

**Comment by FakeItalianMan** [comment]
Thank you so much! Resolved.
