### ISSUE TITLE
Diamond Casino Does Not Work

### ISSUE THREAD

**Issue by BazsYHUN** [Bob74/bob74_ipl#45]
Casino is not loading for me! I tried to enable it than nothing!

![image](https://user-images.githubusercontent.com/63349432/127662085-64395db0-8da7-4888-956c-2db8edaa81f1.png)
![image](https://user-images.githubusercontent.com/63349432/127662222-3c263335-cf7e-455e-b57c-02b1a69cc937.png)

**Comment by MichaelCoding25** [comment]
Are you forcing build 2060?

**Comment by BazsYHUN** [comment]
no

**Comment by MichaelCoding25** [comment]
Well there you go, you can read more about it here: https://i.imgur.com/jyq0pGR.png.

You need to Add `set sv_enforceGameBuild 2060` to your server.cfg or `+set sv_enforceGameBuild 2060` to your launch parameters. (The `.bat` file with which you launch the server)

**Comment by BazsYHUN** [comment]
Thank you!

**Comment by MichaelCoding25** [comment]
If it's been solved, feel free to close the issue.

**Comment by BazsYHUN** [comment]
its not solved. i connect to the server loading screen is on and than ive got a crash, or infinite loading screen.

**Comment by BazsYHUN** [comment]
i dont know what is the problem

**Comment by MichaelCoding25** [comment]
That's nothing to do with this script though, that you gotta figure out on the fivem forums or discord

**Comment by BazsYHUN** [comment]
its working now thank you for your help
i deleted an arcade mlo an dthats solved it
