### ISSUE TITLE
How to load IPL to a specific player?

### ISSUE THREAD

**Issue by TheSpaceGamerV2** [Bob74/bob74_ipl#51]
Hey, I wanted to know how can I load an IPL to a specific player?

**Comment by Bob74** [comment]
The same way as you do to trigger other things to a specific player (show markers, allow a player to press a key at a certain point, etc).
You need to trigger the client function on the desired player from the server.

I don't really know much about this since I've never ran a proper FiveM server.

**Comment by TheSpaceGamerV2** [comment]
Okk i see, is it possible to use your function server side ?

```lua
RegisterServerEvent('loadIPL')
AddEventHandler('loadIPL', function()
   Citizen.CreateThread(function()
     BikerClubhouse1 = exports['bob74_ipl']:GetBikerClubhouse1Object()
      BikerClubhouse1.Walls.Set(BikerClubhouse1.Walls.plan, BikerClubhouse1.Walls.Color.brown, true)
   end)
end)

Something like that ? and after i just need to call the event ?

**Comment by Bob74** [comment]
I suggest you post your question on FiveM forum since I never implemented this ^^

From what I see, I think you could write it simply this way:
```lua
RegisterServerEvent('loadIPL')
AddEventHandler('loadIPL', function()
     BikerClubhouse1 = exports['bob74_ipl']:GetBikerClubhouse1Object()
     BikerClubhouse1.Walls.Set(BikerClubhouse1.Walls.plan, BikerClubhouse1.Walls.Color.brown, true)
end)
```

But I guess you get the spirit :)

**Comment by TheSpaceGamerV2** [comment]
Okk thx ! <3
