### ISSUE TITLE
Attempt to index a nil value (global 'ExecApartement1') 

### ISSUE THREAD

**Issue by TheSpaceGamerV2** [Bob74/bob74_ipl#53]
Hey when i try to change the style of my penthouse i have this error `Attempt to index a nil value (global 'ExecApartement1') `

```lua

      Citizen.CreateThread(function()
              ExecApartment1 = exports['bob74_ipl']:GetExecApartment1Object()
              print(ExecApartement1) -- return nil
              ExecApartment1.Style.Set(ExecApartement1.Style.Theme.vibrant, true)
          end)

**Comment by Bob74** [comment]
Hi, can you check if your resource manifest has the dependency:
`dependency 'bob74_ipl'`

Also, ensure `bob74_ipl` before your custom resource in the server config file.

Do you have the same issue with other interiors?

**Comment by TheSpaceGamerV2** [comment]
Yes in the fxmanifest i have bob74_ipl in dependency, and i ensure bob74_ipl before my script and no i don't have this issue with other interiors

**Comment by Bob74** [comment]
You made a typo: `apartement` -> `apartment`

```lua
Citizen.CreateThread(function()
	ExecApartment1 = exports['bob74_ipl']:GetExecApartment1Object()
	print(ExecApartment1)
	ExecApartment1.Style.Set(ExecApartment1.Style.Theme.vibrant, true)
end)
```

**Comment by TheSpaceGamerV2** [comment]
Oh yeah right sorry ..
