### ISSUE TITLE
teleport out and in to the drug labs

### ISSUE THREAD

**Issue by boxser778** [Bob74/bob74_ipl#54]
hello i was wonder if there is a chance u could help me with this teleport in and out of drug labs by default
some 1 just placed there teleport and i cant find where or how to remove them its a  default teleports in all the labs

**Comment by Bob74** [comment]
Hi, I don't add any marker or teleporting system.
Search for a resource calling [DrawMarker](https://docs.fivem.net/natives/?_0x28477EC23D892089) to find out which one adds the teleport marker.

Also ask directly on FiveM forum since your question is not directly related to this resource.
