### ISSUE TITLE
[Question] So what is up to date?

### ISSUE THREAD

**Issue by nzkfc** [Bob74/bob74_ipl#60]
I've heard many people say to use fivem-ipl but then I see you have updated and lots of posts suggest fivem-ipl is no longer maintained? Is your one now the most up to date?

**Comment by MichaelCoding25** [comment]
This script is indeed more updated than fivem-ipl and even on their forum post they suggest to use this script.
This script is updated to include the casino DLC, while the other one is only updated to the arena wars DLC.

**Comment by Bob74** [comment]
I'm not updating this script myself anymore but when someone push new IPLs, I gladly add them :)
