### ISSUE TITLE
Pillbox Hospital Doors

### ISSUE THREAD

**Issue by Maureks** [Bob74/bob74_ipl#70]
Hello, how can i remove de default doors on pillbox hospital? 

I've tried to add a new hospital map , the doors on the hospital map work ,  but the front doors of the ipl are frozen not letting anyone pass .

How can I resolve this issue ? 

Thanks for the attention !

**Comment by TrAsKiN** [comment]
```lua
CreateThread(function()
    PillboxHospital= exports['bob74_ipl']:GetPillboxHospitalObject()
    PillboxHospital.Enable(false)
end)
```

**Comment by Maureks** [comment]
Thanks ! 
 I should put it like a client.lua and add it to fxmanifest.lua in the map folder, right? 

Sorry

**Comment by Maureks** [comment]
it worked , thank you so much man, much appreciated !

**Comment by MansAnts** [comment]
still having the issue how to fix it

**Comment by frank-scripts** [comment]
> still having the issue how to fix it

You need to find it in the fxmanifest and change it from true to false dont add a second one that will just confuse it and if you dont have a mlo in the city for pill then there you go is another issue and nothing to do with bobs ipl
