### ISSUE TITLE
Dye the windows of the facility

### ISSUE THREAD

**Issue by SpikeScarlatti** [Bob74/bob74_ipl#8]
Hello,
Is it possible to color the windows of the office and the bedroom in facility.lua? This possibility is active on GTA Online? 

Thank you very much.

**Comment by Bob74** [comment]
Hi,
This is possible but not implemented yet, I'll try to add that ;)

**Comment by SpikeScarlatti** [comment]
Thanks for you answer ! 

Good luck 😄

**Comment by Bob74** [comment]
Feature added in the current version (2.0.8).
