### ISSUE TITLE
IPLS not loading on a custom map

### ISSUE THREAD

**Issue by Sam8500** [Bob74/bob74_ipl#81]
Hello, I've downloaded Vice City for my FiveM server. Vice City disables Los Santos but the problem is, it also disables all of the IPLS. Does anyone know a fix for that issue ? The creator of the map told me it has something to do with a .meta file but I haven't been able to find any solution yet.

**Comment by userMacieG** [comment]
Its not an issue of that resource, ask for support on fivem forum: [https://forum.cfx.re/c/server-development/resource-support/47](https://forum.cfx.re/c/server-development/resource-support/47)
