### ISSUE TITLE
Diamond Casino Penthouse Interior

### ISSUE THREAD

**Issue by BraveDevelopment** [Bob74/bob74_ipl#82]
Walls are green/red or blue in penthouse after applying patterns.
![Screenshot 2022-04-17 221235](https://user-images.githubusercontent.com/43207174/163730647-7d82afa5-1ad2-4eee-8cf4-30595d3f7202.png)

**Comment by Bob74** [comment]
Did you try different pattern values and can you post your code?

**Comment by BraveDevelopment** [comment]
> Did you try different pattern values and can you post your code?

I tried every pattern and every penthouse theme.

**Comment by Bob74** [comment]
The whole casino part was not added by me so I didn't see it actually working.
I will try to setup a server to check it.

**Comment by BraveDevelopment** [comment]
> The whole casino part was not added by me so I didn't see it actually working.
> I will try to setup a server to check it.

That would be awesome. Although I’m not the first one having this issue.
[](https://github.com/Bob74/bob74_ipl/issues/39#issue-930456433)

**Comment by Bob74** [comment]
All right, I got something:
![image](https://user-images.githubusercontent.com/9498543/164338859-0c4ae600-b022-4b90-806a-1e7f1e934aca.png)

I will have to make some changes to the penthouse code, but the issue comes from the need to set a color to the patterns:
```lua
DiamondPenthouse.Ipl.Interior.Load()

-- setting a wall style
DiamondPenthouse.Interior.Walls.SetColor(DiamondPenthouse.Colors.timeless)

-- setting carpets patterns
DiamondPenthouse.Interior.Pattern.Set(DiamondPenthouse.Interior.Pattern.pattern01)

-- setting carpets colors
SetInteriorEntitySetColor(DiamondPenthouse.interiorId, DiamondPenthouse.Interior.Pattern.pattern01, DiamondPenthouse.Colors.timeless)


DiamondPenthouse.Interior.SpaBar.Set(DiamondPenthouse.Interior.SpaBar.open)
DiamondPenthouse.Interior.MediaBar.Set(DiamondPenthouse.Interior.MediaBar.open)
DiamondPenthouse.Interior.Dealer.Set(DiamondPenthouse.Interior.Dealer.open)

RefreshInterior(DiamondPenthouse.interiorId)
```

**Comment by Bob74** [comment]
I've updated the repo, could you give it a shot?

**Comment by BraveDevelopment** [comment]
> I've updated the repo, could you give it a shot?
> 
> You can set the color of patterns now:
> 
> ```lua
> LoadDefault = function()
>         local styleColor = DiamondPenthouse.Colors.sharp
>         local stylePattern = DiamondPenthouse.Interior.Pattern.pattern01
>         
>         DiamondPenthouse.Ipl.Interior.Load()
>         
>         DiamondPenthouse.Interior.Walls.SetColor(styleColor)
>         DiamondPenthouse.Interior.Pattern.Set(stylePattern)
>         DiamondPenthouse.Interior.Pattern.SetColor(stylePattern, styleColor)
>         
>         DiamondPenthouse.Interior.SpaBar.Set(DiamondPenthouse.Interior.SpaBar.open)
>         DiamondPenthouse.Interior.MediaBar.Set(DiamondPenthouse.Interior.MediaBar.open)
>         DiamondPenthouse.Interior.Dealer.Set(DiamondPenthouse.Interior.Dealer.open)
> 
>         RefreshInterior(DiamondPenthouse.interiorId)
>     end
> ```

I will try it. Thank you very much!
