### ISSUE TITLE
Incorrect name in wiki

### ISSUE THREAD

**Issue by userMacieG** [Bob74/bob74_ipl#83]
[https://github.com/Bob74/bob74_ipl/wiki/Import-Export:-Vehicle-warehouse](https://github.com/Bob74/bob74_ipl/wiki/Import-Export:-Vehicle-warehouse)
`ImportCEOGarage1` should be replaced to `ImportVehicleWarehouse`

**Comment by Bob74** [comment]
Thanks, it should be fixed :)
