### ISSUE TITLE
Create or duplicate Interior in x location?

### ISSUE THREAD

**Issue by nicxes** [Bob74/bob74_ipl#84]
Hey hi I'm very new on fivem and how maps works and I was wondering if is possible to duplicate a existing interior and set the coordinates, for example in the los santos tuners update you have multiple garages interior, what if I want to move it or change some color from a specific garage?

**Comment by Bob74** [comment]
Hi, it is possible to copy, move or create a brand new location.
These parts of map are *.ymap files and you can edit them as xml (once extracted using OpenIV) or using CodeWalker (excellent tool to see the map in 3D, add, move objects etc.).

It is not really my thing but I think you will be able to find some help on FiveM forums 🙂

**Comment by nicxes** [comment]
Oh perfect! I will investigate it!

And about the current interiors is already loaded from the game, for example los santos tuners is possible to edit one specific garage? For example the color because I'm very sure is not just 1 ipl interior, I think

**Comment by Bob74** [comment]
You should go to the place you want to edit using CodeWalker, select an element and you will see which file loads this element on the left menu.

Therefore you will know which ymap file you have to edit.

**Comment by nicxes** [comment]
Last question! After i duplicate a interior for example.. vehicle warehouse from the DLC import/export, is there any way to modify or integrate it with bobipl? like using this? https://github.com/Bob74/bob74_ipl/wiki/Import-Export:-Vehicle-warehouse

**Comment by Bob74** [comment]
Well, I have no idea how it works with custom maps but if it is handled like native maps, you will have an IPL name (which should be the name of the .ymap file) and an interior Id (I don't know how you get that one, if it is generated by the game, referenced somewhere or hard written in the ymap file).

If you have these elements, you should be able to call the same methods as native IPLs.
