### ISSUE TITLE
Las Lagunas Blvd-Burton "Three palm trees"

### ISSUE THREAD

**Issue by GalenYang** [Bob74/bob74_ipl#88]
_Las Lagunas Blvd-Burton_ **Three palm trees**

**Each of the three trees has a hole in its trunk**

###  Yaw    138.348846

**Comment by Bob74** [comment]
These are the trees?
I don't see hole and I only have `bob74_ipl` running.

![image](https://user-images.githubusercontent.com/9498543/166832058-a736ddb1-8a67-4dbd-9bf7-9bd86f4970ee.png)

**Comment by GalenYang** [comment]
@Bob74 @ Thank you for your patient reply!

I just tried shutting down other resources

Confirm that replaced the latest version of **bob74_ipl-2.0.15**

I also tried both **online** and **story** map modes

FiveM client Ver.5530  
GTAV ver.2545 
Server ver.5402


![2022-05-05 (1)](https://user-images.githubusercontent.com/19515739/166836040-9a203ab4-3a3e-46f3-85ea-7b9a7d1d595a.png)
![2022-05-05 (4)](https://user-images.githubusercontent.com/19515739/166836052-537a35b5-3fb1-4ccd-9833-c5639d403f9a.png)
![2022-05-05 (3)](https://user-images.githubusercontent.com/19515739/166836069-e8797652-458d-4bcf-95b9-f32e56ec9e42.png)
![2022-05-05 (2)](https://user-images.githubusercontent.com/19515739/166836099-292fa4d4-22d5-4a8b-8e7e-a66deb1c5789.png)

**Comment by Bob74** [comment]
That's weird, I've tried commenting  `set sv_enforceGameBuild` too and I still don't have issues.

Did you use a recent FiveM server? Your `server.cfg` file seems a bit "light" compared to the default one ^^

**Comment by GalenYang** [comment]
FiveM server ：Latest Recommended （5402）

server.cfg ：Vanilla Server  （Maybe that's the problem !）



https://docs.fivem.net/docs/server-manual/setting-up-a-server-vanilla/

https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/

![2022-05-05 (5)](https://user-images.githubusercontent.com/19515739/166839433-5df46734-469e-4081-8c52-6461bd9e2832.png)

![2022-05-05 (6)](https://user-images.githubusercontent.com/19515739/166839461-d9cf401f-cef6-46dd-8756-c02b423f1fc3.png)

**Comment by alberttheprince** [comment]
![image](https://github.com/user-attachments/assets/2074fca6-4bf2-414a-bd89-e24ddd9133a4)

I know this thread is old, but this seems to be fixed in the most recent versions. Not sure if anyone was able to recreate it.
