### ISSUE TITLE
Add peds inside IPL

### ISSUE THREAD

**Issue by SpikeScarlatti** [Bob74/bob74_ipl#9]
Hello,

I think we can add peds inside ipl because i have seen it on videos but i can't add them on my servers.

Can you help me.

Thanks you ;-)

**Comment by Bob74** [comment]
Hi, yes it is possible to spawn peds in FiveM but it is not the purpose of this resource.

You need to find how to spawn a ped, this way should work:
```Lua
local model = "U_F_Y_DanceBurl_01"
local pos = GetEntityCoords(playerPed)

RequestModel(model)
while not HasModelLoaded(model) do Wait(1) end

CreatePed(4, model, pos.x, pos.y, pos.z, 0.0, true, true)
```
