### ISSUE TITLE
Missing roads

### ISSUE THREAD

**Issue by lildiznick** [Bob74/bob74_ipl#92]
I recently updated to build 2545 and have huge holes in the roads as shown below.  I switched back to build 2372 and the holes were gone.  I'm currently running version 2.0.15 of bob74_ipl.  Everyone in server sees the holes the same as I do.  I've also tried running FiveM in beta and the canary version.

![FiveM® by Cfx re -  Wild West Coast RP qbCore Life RP Server BETA 5_19_2022 5_41_06 AM](https://user-images.githubusercontent.com/68559172/169286574-463872f7-8dfd-4027-8b9d-29b2943fb5f5.png)
![FiveM® by Cfx re -  Wild West Coast RP qbCore Life RP Server BETA 5_19_2022 5_40_12 AM](https://user-images.githubusercontent.com/68559172/169286577-859f0919-7607-4dae-82cc-2284e8d6d4a6.png)
![FiveM® by Cfx re -  Wild West Coast RP qbCore Life RP Server BETA 5_19_2022 5_40_44 AM](https://user-images.githubusercontent.com/68559172/169286580-42a04cb6-b5c7-49b9-82ec-f900d12fb2bd.png)

**Comment by Bob74** [comment]
Well I'm not having any issue running this version:
![image](https://user-images.githubusercontent.com/9498543/169869517-f20414eb-a51f-4614-9519-52e808c2f239.png)
![image](https://user-images.githubusercontent.com/9498543/169869828-97b4a85c-95a8-4925-a878-aa28221aa7c7.png)

Did you try disabling other resources? If you are using custom mappings, it often leads to collisions issues with the map.

**Comment by peppinoita** [comment]
Hi. This issue is related to occlusion change in new game build so you have to modify add-on maps

**Comment by lildiznick** [comment]
It was caused by a custom MLO building in that area.  Thanks guys!
