### ISSUE TITLE
unable to Use/Fire weapons inside apartments

### ISSUE THREAD

**Issue by mrtylergamer** [Bob74/bob74_ipl#96]
**Describe the bug**
Being totally unable to use any kind of weapons within the apartments 

**To Reproduce**
Goto an apartment and attempt to use any weapon (Pistol, smg, Assault Rife) (Mainly sighted at tinsel Towers)

**Expected behavior**
Be able to use a weapon within the apartment

**Screenshots**
![image](https://user-images.githubusercontent.com/49989225/171297781-c4576812-81cc-4bb4-8a23-fd4b60a26173.png)

**Versions**
 - Game build version 2372
 - Resource version 2.0.10a

**Comment by mrtylergamer** [comment]
Ahh right do you know any way to change that (i have aeen videos of people able to use guns inside)

**Comment by TayMcKenzieNZ** [comment]
I'm on the latest gamebuild and can shoot etc inside buildings. You obviously have a script that prevents you. GTA online has scripts, but nothing within bob74_ipl is causing this. Double check your resources
