### ISSUE TITLE
Falling Through Map at Jewelry Store Stairs

### ISSUE THREAD

**Issue by sinphoenix** [Bob74/bob74_ipl#98]
**First of all**
Did you try disabling `bob74_ipl` to see if the issue is still there? Yes
Did you use the latest version of `bob74_ipl` ? Yes
Did you use an up to date server [artifact](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) ? Yes

**Describe the bug**
Fall Through map at back stairs at Jewelry Store

Also, beside the store is gone. ScreenShot 2

**To Reproduce**
Back Stair case at Jewelry Store
-602.92, -297.4. 34.74, 114.7 - first landing
cant get for second because you fall through

**Expected behavior**
Walking up the stair way to go to Jewelry Store and you fall through the first landing but not all the way. Second landing you fall completely through the stairway.

**Screenshots**
[Screenshot](https://cdn.discordapp.com/attachments/838980286263984189/999723334755430460/20220721110129_1.jpg)

[SCREENSHOT2](https://cdn.discordapp.com/attachments/962435283289243668/999725253817282790/unknown.png)

Video:
https://medal.tv/games/gta-v/clips/tgM1zw4qgwPbM/d13377wqwMtx?invite=cr-MSx6eDMsMjI1NjQ0OTIs

**Versions**
 - 2545
 - Latest, added into server today

**Comment by sinphoenix** [comment]
its actually from past the Jewelry store to the road using stairs.

**Comment by peppinoita** [comment]
are you using a apple store map?

**Comment by sinphoenix** [comment]
not at all.. Freash install of QBCore

MAPS USED:
-GABZ MAPS- (None near location, talked to their support team nothing to cause this)
Hen House (Its on the other side of the map)
Cookies

**Comment by sinphoenix** [comment]
just replaced BOB_ipl

and same issue

**Comment by sinphoenix** [comment]
I fixed it.. It was a Random iFruit Store there. Thank you and sorry for the ticket!
