### ISSUE TITLE
The Criminal Enterprises (mpsum2)

### ISSUE THREAD

**Issue by NovationNL** [Bob74/bob74_ipl#99]
Hi, can you add the new interiors of The Criminal Enterprises released this month?

**Comment by BaziForYou** [comment]
will do that maybe tonight or tomorrow

**Comment by BaziForYou** [comment]
request pulled https://github.com/Bob74/bob74_ipl/pull/100

**Comment by TayMcKenzieNZ** [comment]
I have updated my game, artifacts, and enforced the correct gamebuild, but they don't load. I'm just standing on nothing. Do we have to set them up or something?

**Comment by Bob74** [comment]
Merged in 2.1.0
